export const UPDATE_STOCK_DATA = "UPDATE_STOCK_DATA";
export const UPDATE_TICKER_DATA = "UPDATE_TICKER_DATA"; 
export const UPDATE_MODAL_MESSAGE = "UPDATE_MODAL_MESSAGE";
export const RESET_MODAL_MESSAGE = "RESET_MODAL_MESSAGE";
export const RESET_STOCK_DATA = "RESET_STOCK_DATA";